name: Convert BSE CSV to JSON Daily

on:
  schedule:
    - cron: '00 16 * * *'  # 9:30 PM IST = 4:00 PM UTC
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run conversion script
        run: python convert_csv_to_json_bse.py
