name: Daily NSE + BSE Data Import

# Run at 9:30 PM IST every day (15:00 UTC)
on:
  schedule:
    - cron: '30 15 * * *'

jobs:
  import_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run NSE script
        run: python3 nse_surveillance_data/nse_download.py

      - name: Run BSE script
        run: python3 bse_surveillance_data/bse_data_extraction_code1.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated daily import: NSE + BSE data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

