name: Daily NSE + BSE Data Import

on:
  schedule:
    - cron: '00 16 * * *'  # 9:30 PM IST daily
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests selenium webdriver-manager

    - name: Run NSE download
      run: python3 nse_surveillance_data/nse_download.py

    - name: Run BSE download
      run: python3 bse_surveillance_data/bse_data_extraction_code1.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "🤖 Daily update: NSE and BSE data" || echo "No changes to commit"
        git push
